services: 
  backend:
      image: project_name_backend
      hostname: backend
      restart: always
      environment:
        BE_PORT: 8001
        BE_HOST: 172.30.1.7  
      ports:
        - "9001:8001"
      volumes:
        - ../Data:/landing
      networks:
        servnet:
          ipv4_address: 172.30.1.7
  frontend:
      image: project_name_frontend
      hostname: frontend
      restart: always
      depends_on:
        - backend
      environment:
        FE_PORT: 8000
        FE_HOST: 172.30.1.8
        BE_PORT: 8001
        BE_HOST : 172.30.1.7
      ports:
        - "9000:8000"
      extra_hosts:
        - "backend:172.30.1.7"
      networks:
        servnet:
          ipv4_address: 172.30.1.8
volumes:
  pg_data:

networks:
  servnet:
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16