services: 
  backend:
      image: project_name_backend
      hostname: backend
      restart: always
      environment:
        BE_PORT: 8001
        BE_HOST: 173.31.1.7  
        RUN_NAME: 'run_project_name'
        EXPERIMENT_NAME: 'experiment_project_name'
        MLFLOW_REMOTE_SERVER_URI: 'http://127.0.0.1:1234'
        REGISTERED_MODEL_NAME: 'project_name_model'
      ports:
        - "9101:8001"
        - "9102:1234"
      volumes:
        - ../Data:/landing
      networks:
        servnet:
          ipv4_address: 173.31.1.7
  frontend:
      image: project_name_frontend
      hostname: frontend
      restart: always
      depends_on:
        - backend
      environment:
        FE_PORT: 8000
        FE_HOST: 173.31.1.8
        BE_PORT: 8001
        BE_HOST : 173.31.1.7
      ports:
        - "9100:8000"
      extra_hosts:
        - "backend:173.31.1.7"
      networks:
        servnet:
          ipv4_address: 173.31.1.8
volumes:
  pg_data:

networks:
  servnet:
    ipam:
      driver: default
      config:
        - subnet: 173.31.0.0/16