services: 
  backend:
      image: project_name_backend
      hostname: backend
      restart: always
      environment:
        BE_LOCAL_IP: 172.29.1.7
        BE_LOCAL_HOSTNAME: backend
        BE_PORT: 8001
        BE_HOST : 127.0.0.1
        
      ports:
        - "8001:8001"
      volumes:
        - ../Data:/landing
      networks:
        sparknet:
          ipv4_address: 172.29.1.7
  frontend:
      image: project_name_frontend
      hostname: frontend
      restart: always
      environment:
        FE_LOCAL_IP: 172.29.1.8
        FE_LOCAL_HOSTNAME: frontend
        FE_PORT: 8000
        FE_HOST : 127.0.0.1
      ports:
        - "8000:8000"
      networks:
        sparknet:
          ipv4_address: 172.29.1.8
volumes:
  pg_data:

networks:
  sparknet:
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/16