services: 
  backend:
      image: lanteklcorzo001/mlops-repo-structure-template-be
      hostname: backend
      restart: always
      environment:
        BE_PORT: 8001
        BE_HOST: 173.31.1.7  
        RUN_NAME: run_project_name
        EXPERIMENT_NAME: experiment_project_name
        MLFLOW_REMOTE_SERVER_URI: http://173.31.1.7:1234
        REGISTERED_MODEL_NAME: project_name_model
      ports:
        - "9102:1234"
      volumes:
        - pg_data:/BackEnd/artifacts/
        - ./Data/:/BackEnd/Data/
      networks:
        servnet:
          ipv4_address: 173.31.1.7
  frontend:
      image: lanteklcorzo001/mlops-repo-structure-template-fe
      hostname: frontend
      restart: always
      depends_on:
        - backend
      environment:
        FE_PORT: 8000
        FE_HOST: 173.31.1.8
        BE_PORT: 8001
        BE_HOST: 173.31.1.7
      extra_hosts:
        - "backend:173.31.1.7"
      ports:
        - "8000:8000"
      networks:
        servnet:
          ipv4_address: 173.31.1.8
  nginx:
    image: nginx:1.21.6-alpine
    ports:
      - 980:80
    depends_on:
      - frontend
      - oauth2-proxy
    restart: always
    networks:
      servnet:
        ipv4_address: 173.31.1.9
    volumes:
      - ./nginx-default.conf.template:/etc/nginx/templates/default.conf.template
      - ./certs:/etc/nginx/certs

  oauth2-proxy:
    image:  quay.io/oauth2-proxy/oauth2-proxy
    hostname: oauth2-proxy
    restart: always
    env_file:
      - .env 
    command:
      - --http-address
      - 0.0.0.0:4180 
    environment:
      OAUTH2_PROXY_PROVIDER: github
      OAUTH2_PROXY_UPSTREAM: http://frontend:8000/
      OAUTH2_PROXY_PROVIDER_DISPLAY_NAME: GitHub 
      OAUTH2_PROXY_REDIRECT_URL: http://localhost:980/oauth2/callback

      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      OAUTH2_PROXY_PASS_ACCESS_TOKEN: true 
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:4180


    networks:
      servnet:
        ipv4_address: 173.31.1.10

volumes:
  pg_data:
  # driver: local

networks:
  servnet:
    ipam:
      driver: default
      config:
        - subnet: 173.31.0.0/16