FROM continuumio/miniconda3:latest

COPY . /BackEnd
WORKDIR /BackEnd


COPY ./be_entrypoint.sh ./entrypoint.sh
RUN chmod +x ./entrypoint.sh
RUN conda env create -f Settings/Code/code_development_env.yaml
ENTRYPOINT ["./entrypoint.sh"]